### ISSUE TITLE
School Points: Spike User tracking

### ISSUE THREAD

**Issue by cressie176** [tes/app-house-points#15]
### Why
We need to demonstrate how to perform user tracking on third party sites. This can be problematic due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and should provide an example of how to use send tracking events to Tes. 

### Acceptance Criteria
- [x] Track landing page (logged off)
- [x] Track landing page (logged on)
- [x] Track house point allocation
- [x] See @mrose86 for what details to track. It's likely we'll need to include a device id (i.e. a browser fingerprint), user tesUserId and event id.
- [x] Document how to use MZ with a 3rd party in the project readme

### Guidance
Internally we use [mz](https://github.com/tes/mz) however this is a private module so could consider making it public.

**Comment by hustler** [comment]
//cc @mrose86 this is the ticket we're using to track what I was talking about yesterday. If you have any thoughts put them.

**Comment by hustler** [comment]
@mrose86 sorry for spam :( 

demo site here: https://tes-house-points.herokuapp.com

I've added your marvin_rose credentials to Z H2o test school, so you can log into the demo app if required.

**Comment by mrose86** [comment]
@hustler thank you

**Comment by mrose86** [comment]
@huster less is more. Please see the deck below:

https://docs.google.com/presentation/d/1j07IHBKXJN2akRT4TpTLviqzo5GIHSwt-Mwd_mj6TGw/edit?usp=sharing

**Comment by hustler** [comment]
@mrose86 this is great stuff. thank you! I wonder if there is any value in capturing the school Id used by the 3rd party e.g. `localSchoolId: z2`  in addition to the Tes online Id in the employer details section?

**Comment by mrose86** [comment]
@hustler probably (sorry, I wasn't aware of that). If we are to capture that, then it should be in the event_payload column of the event_stream. I don't think there is another column that is appropriate for this information

**Comment by hustler** [comment]
@mrose86 I've added mz to the app. I've fired off a couple of events. How do we go about checking its ok? I'm not 100% certain everything infrastructure wise is setup yet so dont be surprised if nothing coming through.

**Comment by mrose86** [comment]
@hustler I will have a check now

**Comment by mrose86** [comment]
@hustler the only data coming through to the event_stream is the login success. No data from the new House Points pages yet

**Comment by hustler** [comment]
@mrose86 mz tracking now working. I've checked the event stream and live events now coming through. Thanks for all your help!

**Comment by mrose86** [comment]
Any time @hustler. I have had a check and I can confirm that all the important fields populate (e.g. employer ID). Only one unimportant detail is I cannot tell which house received a vote, or whether it was upvoted or downvoted

**Comment by hustler** [comment]
@mrose86 this is an example of the event for the 'CLICK' downvote, the `page.eventData` has the `title: targaryen-downvote`. I wasn't sure this was correct. No biggy as you say, as the proof here is the end-end solution. 

```JSON
{
  "asset": {
    "type": "house_points"
  },
  "cid": "",
  "event": "click",
  "eventData": {
    "eventData": {
      "title": "targaryen-downvote"
    }
  },
  "page": {
    "employerData": {
      "employerID": 1058690
    },
    "referrer": {},
    "section": "schools",
    "subsection": "portal",
    "thirdPartyAnalyticsDisabled": true,
    "type": "house_points"
  },
  "referrer": "https://tes-house-points.herokuapp.com/schools/z2",
  "screen": {
    "availHeight": 1417,
    "availLeft": 0,
    "availTop": 23,
    "availWidth": 2560,
    "height": 1440,
    "innerHeight": 1306,
    "innerWidth": 764,
    "orientation_angle": 0,
    "orientation_type": "landscape-primary",
    "width": 2560
  },
  "url": "https://tes-house-points.herokuapp.com/schools/z2",
  "user": {
    "id": "1081298"
  }
}
```
